version: '3'

services:

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local_postgresql
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
